### ISSUE TITLE
Урок №4. Клик на любую кнопку приводит к странице 404 – Not Found.

### ISSUE THREAD

**Issue by ikonovi** [triodjangopiter/servlet-tutorial#2]
В коде JSP-страниц не учтен context root веб приложения - по умолчанию /servlet-tutorial .

**Comment by PavelRavvich** [comment]
Если я верно вас понял, то дело в настройке IDE.  Подробная инструкция в первых уроках. Сейчас приложение расчитывает что вы установили контекст `/`
Но вы так-же можете использовать `${pageContext.request.contextPath}`, для получения контекста, и указать эту переменную префиксом ссылок в JSP. Это будет более универсально.
Или лучше присылайте pull request с улучшением. :)

**Comment by PavelRavvich** [comment]
Спасибо!
https://github.com/triodjangopiter/servlet-tutorial/pull/3
